version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 1
    groups:
      all-pip-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 1
    groups:
      all-actions:
        patterns:
          - "*"
